### ISSUE TITLE
Export Angle constructor

### ISSUE THREAD

**Issue by treeowl** [diagrams/diagrams#13]
Since an angle is really and truly just a number, I think the `Radians` constructor should be exposed. I also think you should expose more instances:

```haskell
deriving instance Num n => Num (Angle n)
deriving instance Real n => Real (Angle n)
deriving instance Fractional n => Fractional (Angle n)
deriving instance RealFrac n => RealFrac (Angle n)
deriving instance RealFloat n => RealFloat (Angle n)
```

**Comment by byorgey** [comment]
Thanks for bringing this up.  Exposing the constructor could make sense though I kind of lean towards keeping it abstract.  Why do you want it?

I really don't want to export those instances since *e.g.* multiplying two angles does not make sense.

**Comment by treeowl** [comment]
You may be right about the instances. Less because they don't make sense
than because they're likely to lead to mistakes, but that's still a valid
reason to avoid them. And I guess keeping the constructor abstract allows
you the flexibility to do things like caching sine and cosine if you decide
that sort of thing is useful.

**Comment by byorgey** [comment]
Yeah, I think that's what I meant by saying "multiplying angles does not make sense" --- if you multiply two angles, it means you are Doing Something Wrong™ and the type checker ought to stop you.  And yes, keeping Angle abstract means we can change representation later, and it provides a more consistent API since there are really three views on Angles and there's no particular reason to privilege one over the others (though to be fair the radians view is already privileged a bit via the `Show` instance).

Just for completeness, and to help anyone else who finds this issue later: 

* `Angles` have `Monoid` and `Additive` instances, so you can combine them with `(<>)` (which adds them), or add and subtract with `(^+^)` and `(^-^)`.
* To subtract two `Direction`s to get an `Angle`, you can use `angleBetweenDirs` (absolute value) or `signedAngleBetweenDirs` (counterclockwise = positive).  
* To add an `Angle` and a `Direction` you can `rotate` the `Direction` by the `Angle`.
* To construct an `Angle`, use `@@` along with `rad`, `deg`, or `turn`, e.g. `(0.5 @@ turn) ^+^ (2 @@ rad)`.
* To deconstruct an `Angle`, use e.g. `angle ^. deg` or `view deg`.  With the `ViewPatterns` extension you can write things like
```
f :: Angle Double -> ...
f (view deg -> d) = ... d ...
```

**Comment by treeowl** [comment]
Well, I disagree with the claim that we shouldn't privilege one view over
the others, but that's neither here nor there.

**Comment by byorgey** [comment]
OK, that's fair.  Anyway, thanks again for the suggestion.  It's always good to think through these sorts of things even if we ultimately end up not making any changes.
