### ISSUE TITLE
Archived?

### ISSUE THREAD

**Issue by cdupont** [diagrams/diagrams#27]
Hello,
I see that the website is "archived": http://projects.haskell.org/diagrams/
Is it intended?

**Comment by byorgey** [comment]
Everything on projects.haskell.org was archived when that service was
decommissioned.  The new diagrams website is at  diagrams.github.io .

**Comment by edo-codes** [comment]
The homepage link on the github organization, the main package documentation and the website link Hackage all still point to projects.haskell.org. This causes MathJax to fail to load on those pages due to a mixed content (http/https) error, because the pages are served with https, but the <script> tag tries to load an http version of the MathJax javascript.

**Comment by byorgey** [comment]
Thanks for pointing these out.  I guess I didn't realize how many places
still had the old URL! I just fixed the github organization homepage link
and plan to fix up the other links soon.

-Brent
