### ISSUE TITLE
interactive (in the sense of JS-y stuff) diagrams?

### ISSUE THREAD

**Issue by ym-han** [diagrams/diagrams#33]
Hi, this looks like a great library. Was just wondering: is it possible to use this to produce interactive, reactive diagrams that allow for things like:

* redrawing dynamically when a user, e.g., clicks on a button in a browser
* getting (customized) hover mouseovers over specific parts of the diagram 

(This qn has some overlap with #28, but is, I think, really its own topic.)

**Comment by byorgey** [comment]
Hi @ym-han , as for the first bullet point, sure, but I don't think that's the responsibility of this library.  Just write some wrapper code that handles button clicks and uses this library to generate a new image.  (Note that although a lot of this library is oriented towards creating standalone programs that just generate an image file, it is also possible to use it via an API and to generate images in memory without saving to a file.)

As for the second bullet point, this blog post may be helpful: https://diagrams.github.io/blog/2015-04-30-GTK-coordinates.html  .  You may also want to take a look at the capabilities of the SVG backend: https://hackage.haskell.org/package/diagrams-svg-1.4.3.1/docs/Diagrams-Backend-SVG.html .  I forget exactly what is possible but I think you can use it to embed enough information in the generated SVG such that you can then use JS/CSS to specify what happens when the user mouses over certain parts of the diagram etc.

**Comment by ym-han** [comment]
Thank you!!!!
