### ISSUE TITLE
Travis should test GHC-7.8.4, 7.10.1

### ISSUE THREAD

**Issue by FranklinChen** [diagrams/diagrams#8]
The Travis build is failing. Also, GHC 7.8.4 and 7.10.1 are not yet being tested here.

**Comment by bergey** [comment]
Since `diagrams` is just a wrapper to install [`diagrams-core`](https://travis-ci.org/diagrams/diagrams-core), [`diagrams-lib`](https://travis-ci.org/diagrams/diagrams-lib), and [`diagrams-contrib`](https://travis-ci.org/diagrams/diagrams-contrib) with one command, the travis build isn't very meaningful.  In particular, it only builds when we push a commit to this repo, which rarely happens.  The individual builds (linked above) are succeeding on GHC-7.8.4, and the fixes for 7.10.1 should land before GHC-7.10.1 comes out.

I'm renaming this issue as a reminder to update the .travis file & rebuild once the dependencies are building with GHC-7.10.

**Comment by bitemyapp** [comment]
@bergey if it helps, Bloodhound has a travis containers compatible build that handles multiple GHC versions: https://github.com/bitemyapp/bloodhound/blob/master/.travis.yml

**Comment by byorgey** [comment]
I note that hvr has also updated his repo https://github.com/hvr/multi-ghc-travis to even have a script that automatically generates (from the tested-with field in the .cabal file) a multi-GHC matrix build using the new travis container infrastructure.  I used it the other day to set up travis builds for xmonad.
